name: Build

on:
  push:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Install base php environment
      run: |
        set -o nounset
        set -o errexit
        sudo apt-get update
        sudo apt-get install -y \
          autoconf \
          zlib1g-dev \
          php7.2-cli \
          php7.2-dev \
          php-pear
          
        pecl version
        php -v
          
          
    - name: Install and compile grpc
      run: |
        set -o nounset
        set -o errexit
        pecl version
        pecl install grpc
        pecl info grpc
        ls -lh /usr/lib/php/20170718/

    - name: Install and compile protobuf
      run: |
        set -o nounset
        set -o errexit
        pecl install protobuf
        pecl info protobuf
        ls -lh /usr/lib/php/20170718/
        
