name: Build

on:
  push:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Install base php environment
      run: |
        set -o nounset
        set -o errexit
        sudo apt-get update
        sudo apt-get install -y \
          autoconf \
          zlib1g-dev \
          php7.2-cli \
          php7.2-dev \
          php-pear
        
        sudo update-alternatives --set php /usr/bin/php7.2
        sudo update-alternatives --set phpize /usr/bin/phpize7.2
        sudo update-alternatives --set php-config /usr/bin/php-config7.2
      
        mkdir -p /tmp/pear/cache
        
    - name: Display php versions and configs    
      run: |
        php -v
        pecl version
        pecl config-show
          
    - name: Install and compile grpc
      run: |
        set -o nounset
        set -o errexit
        sudo pecl install grpc
        pecl info grpc
        ls -lh /usr/lib/php/20170718/
        
    - name: Install and compile protobuf
      run: |
        set -o nounset
        set -o errexit
        sudo pecl install protobuf
        pecl info protobuf
        ls -lh /usr/lib/php/20170718/
        
    - name: Strip debug symbols from grpc and protobuf
      run: |
        set -o nounset
        set -o errexit
        sudo strip --strip-debug /usr/lib/php/20170718/grpc.so
        sudo strip --strip-debug /usr/lib/php/20170718/protobuf.so
        
        ls -lh /usr/lib/php/20170718/
        
    - name: Rename package versions
      run: |
        set -o nounset
        set -o errexit
        mkdir artifacts
        cp /usr/lib/php/20170718/grpc.so artifacts/grpc-php72-1.30.0.so
        cp /usr/lib/php/20170718/protobuf.so artifacts/protobuf-php72-3.12.3.so
        
    - name: Publish artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ext-bins
        path: artifacts/   
